name = "DirectTrajOpt"
uuid = "c823fa1f-8872-4af5-b810-2b9b72bbbf56"
version = "0.8.7"
authors = ["Aaron Trowbridge <aaron.j.trowbridge@gmail.com> and contributors"]

[deps]
ExponentialAction = "e24c0720-ea99-47e8-929e-571b494574d3"
FiniteDiff = "6a86dc24-6348-571c-b903-95158fe2bd41"
ForwardDiff = "f6369f11-7733-5829-9624-2563aa707210"
Ipopt = "b6b21f68-93f8-5de0-b562-5493be1d77c9"
LazyArrays = "5078a376-72f3-5289-bfd5-ec5146d43c02"
Libdl = "8f399da3-3557-5675-b5ff-fb832c97cbdb"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
MathOptInterface = "b8f27783-ece8-5eb3-8dc8-9495eed66fee"
NamedTrajectories = "538bc3a1-5ab9-4fc3-b776-35ca1e893e08"
OrdinaryDiffEqTsit5 = "b1df2697-797e-41e3-8120-5422d3b24e4a"
Reexport = "189a3867-3050-52da-a836-e630ba90ab69"
SciMLBase = "0bca4576-84f4-4d90-8ffe-ffa030f20462"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
TestItemRunner = "f8b46487-2199-4994-9208-9a1283c18c0a"
TestItems = "1c621080-faea-4a02-84b6-bbd5e436b8fe"
TrajectoryIndexingUtils = "6dad8b7f-dd9a-4c28-9b70-85b9a079bfc8"

[compat]
ExponentialAction = "0.2"
FiniteDiff = "2.29"
ForwardDiff = "1.3"
Ipopt = "1.14"
LazyArrays = "2.9"
Libdl = "1.10, 1.11, 1.12"
LinearAlgebra = "1.10, 1.11, 1.12"
MathOptInterface = "1.49"
NamedTrajectories = "0.8"
OrdinaryDiffEqTsit5 = "1.9"
Reexport = "1.2"
SciMLBase = "2.145.0 - 2.145, 2"
SparseArrays = "1.10, 1.11, 1.12"
Test = "1.10, 1.11, 1.12"
TestItemRunner = "1.1"
TestItems = "1.0"
TrajectoryIndexingUtils = "0.1"
julia = "1.10, 1.11, 1.12"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
